name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    name: Build and Deploy Monorepo (Backend + Frontend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit on any error

            cd ~/task-tracker-sre

            # Pull latest code
            git pull origin main

            # Stop existing containers and free port 3000 (if needed)
            sudo fuser -k 3000/tcp || true

            docker compose down || true

            docker ps -q | xargs -r docker stop || true
            docker ps -aq | xargs -r docker rm || true

            # Build and run containers
            docker compose up -d --build
          EOF
